routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MahasiswaController;
use App\Http\Controllers\MatkulController;
use App\Http\Controllers\NilaiController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', [App\Http\Controllers\mhscekController::class, 'index'])->name('mhscek');

// Auth::routes();
Route::prefix('wp-admin')->group(function () {
    Auth::routes();
});
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('mahasiswa', MahasiswaController::class);
Route::resource('matkul', MatkulController::class);
Route::resource('nilai', NilaiController::class);
Route::get('/profile/index', [App\Http\Controllers\ProfileController::class, 'index'])->name('profile.index');
Route::get('/cek', [App\Http\Controllers\mhscekController::class, 'show'])->name('mhscek.show');
Route::get('/analisis', [App\Http\Controllers\analisisController::class, 'index'])->name('analisis.index');

app/Models/matkul.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class matkul extends Model
{
    protected $table = 'matkul';
    protected $guarded = ['id'];
}

app/Http/Controllers/MatkulController.php
<?php

namespace App\Http\Controllers;

use App\Models\matkul;
use Illuminate\Http\Request;

class MatkulController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index()
    {
        $matkul = matkul::all();
        return view('matkul.index', compact(
            'matkul'
        ));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $model = new matkul;
        return view('matkul.create', compact(
            'model'
        ));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'kode' => 'required|unique:matkul',
            'nama' => 'required',
            'sks' => 'required|max:1',
            'deskripsi' => 'required|max:150',
        ],
        [
            'kode.required' => 'Kode Mata Kuliah tidak boleh kosong',
            'kode.unique' => 'Kode Mata Kuliah sudah digunakan',
            'nama.required' => 'Nama Mata Kuliah tidak boleh kosong',
            'sks.required' => 'SKS tidak boleh kosong',
            'sks.max' => 'Maximal 1 karakter',
            'deskripsi.required' => 'Deskripsi tidak boleh kosong',
            'deskripsi.max' => 'Maximal 150 karakter',
        ]);

        matkul::create([
            "kode" => $request['kode'],
            "nama" => $request['nama'],
            "sks" => $request['sks'],
            "deskripsi" => $request['deskripsi']
        ]);

        return redirect('matkul');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\matkul  $matkul
     * @return \Illuminate\Http\Response
     */
    public function show(matkul $matkul)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\matkul  $matkul
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $matkul = matkul::where('id', $id)->first();
        return view('matkul.edit', compact('matkul'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\matkul  $matkul
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'kode' => 'required|unique:matkul',
            'nama' => 'required',
            'sks' => 'required|max:1',
            'deskripsi' => 'required|max:150',
        ],
        [
            'kode.required' => 'Kode Mata Kuliah tidak boleh kosong',
            'kode.unique' => 'Kode Mata Kuliah sudah digunakan',
            'nama.required' => 'Nama Mata Kuliah tidak boleh kosong',
            'sks.required' => 'SKS tidak boleh kosong',
            'sks.max' => 'Maximal 1 karakter',
            'deskripsi.required' => 'Deskripsi tidak boleh kosong',
            'deskripsi.max' => 'Maximal 150 karakter',
        ]);

        $matkul = matkul::where('id', $id)->update([
            "kode" => $request['kode'],
            "nama" => $request['nama'],
            "sks" => $request['sks'],
            "deskripsi" => $request['deskripsi']
        ]);

        return redirect('matkul');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\matkul  $matkul
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $query = matkul::where('id', $id)->delete();
        return redirect('matkul');
    }
}

resources/views/matkul/create.blade.php
@extends('partial.master')

@section('content')
<div class="content">
    <div class="page-inner">
        <div class="page-header">
            <h4 class="page-title">Tambah Data Mata Kuliah</h4>   
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">Form Tambah Data</div>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('matkul.store') }}" method="POST">
                            @csrf
                                <div class="form-group">
                                    <label>Kode</label>
                                    <input type="text" name="kode" class="form-control @error('kode') is-invalid @enderror" placeholder="Kode">
                                    @error('kode')
                                        <div class="invalid-feedback">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label>Nama</label>
                                    <input type="text" name="nama" class="form-control @error('nama') is-invalid @enderror" placeholder="Nama Mata Kuliah">
                                    @error('nama')
                                        <div class="invalid-feedback">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label>SKS</label>
                                    <input type="text" name="sks" class="form-control @error('sks') is-invalid @enderror" placeholder="SKS">
                                    @error('sks')
                                        <div class="invalid-feedback">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label>Deskripsi </label>
                                    <i> ( Maksimal 150 Karakter )</i>
                                    <input type="text" name="deskripsi" class="form-control @error('deskripsi') is-invalid @enderror" placeholder="Deskripsi dari Mata Kuliah tersebut">
                                    @error('deskripsi')
                                        <div class="invalid-feedback">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="card-action">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                    <a href="{{route('matkul.index')}}"><button type="button" class="btn btn-danger">Cancel</button></a>
                                </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/matkul/edit.blade.php
@extends('partial.master')

@section('content')
<div class="content">
    <div class="page-inner">
        <div class="page-header">
            <h4 class="page-title">Edit Data Mata Kuliah</h4>   
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">Form Edit Data</div>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('matkul.update', $matkul->id) }}" method="POST">
                            @csrf
                            @method('PUT')
                                <div class="form-group">
                                    <label>Kode</label>
                                    <input type="text" name="kode" class="form-control @error('kode') is-invalid @enderror" placeholder="Kode" value="{{old('kode', $matkul->kode)}}">
                                    @error('kode')
                                        <div class="invalid-feedback">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label>Nama</label>
                                    <input type="text" name="nama" class="form-control @error('nama') is-invalid @enderror" placeholder="Nama Mata Kuliah" value="{{old('nama', $matkul->nama)}}">
                                    @error('nama')
                                        <div class="invalid-feedback">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label>SKS</label>
                                    <input type="text" name="sks" class="form-control @error('sks') is-invalid @enderror" placeholder="SKS" value="{{old('sks', $matkul->sks)}}">
                                    @error('sks')
                                        <div class="invalid-feedback">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label>Deskripsi</label>
                                    <input type="text" name="deskripsi" class="form-control @error('deskripsi') is-invalid @enderror" placeholder="Deskripsi dari Mata Kuliah tersebut" value="{{old('deskripsi', $matkul->deskripsi)}}">
                                    @error('deskripsi')
                                        <div class="invalid-feedback">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="card-action">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                    <a href="{{route('matkul.index')}}"><button type="button" class="btn btn-danger">Cancel</button></a>
                                </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/matkul/index.blade.php
@extends('partial.master')
@push('style')
    <link rel="stylesheet" href="{{ asset('layout/assets/css/lib/datatable/dataTables.bootstrap.min.css') }}">
@endpush
@section('content')
    <div class="content">
        <div class="animated fadeIn">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="d-flex align-items-center">
                                <h4 class="card-title">Data Mata Kuliah</h4>
                                
                                {{-- <a href="{{ route('matkul.create') }}" class="btn btn-primary btn-round ml-auto">
                                    Tambah Data  
                                </a> --}}
                                
                            </div>
                        </div>
                        <div class="card-body">
                            <table id="bootstrap-data-table" class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th width=5%>No</th>
                                        <th width=15%>Kode</th>
                                        <th width=25%>Nama Matkul</th>
                                        <th width=10%>SKS</th>
                                        <th width=30%>Deskripsi</th>
                                        <th width=15%>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($matkul as $key=>$data)
                                    <tr>
                                        <td>{{ $data->id }}</td>
                                        <td>{{ $data->kode }}</td>
                                        <td>{{ $data->nama }}</td>
                                        <td>{{ $data->sks }}</td>
                                        <td>{{ $data->deskripsi }}</td>
                                        <td>
                                            <form action="{{route('matkul.destroy', $data->id)}}" method="POST">
                                                @csrf
                                                @method('DELETE')
                                            <a href="{{ route('matkul.edit', $data->id)}}" class="btn btn-primary btn-sm"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                                            <button type="submit" class="btn btn-danger my-1 btn-sm fa fa-trash"></button>
                                            </form>
                                        </td>
                                    </tr>    
                                    @endforeach          
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>


            </div>
        </div><!-- .animated -->
    </div>
@endsection

@push('scripts')
    <script src="{{ asset('layout/assets/js/lib/data-table/dataTables.bootstrap.min.js') }}"></script>
    <script src="{{ asset('layout/assets/js/lib/data-table/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('layout/assets/js/lib/data-table/buttons.bootstrap.min.js') }}"></script>
    <script src="{{ asset('layout/assets/js/lib/data-table/jszip.min.js') }}"></script>
    <script src="{{ asset('layout/assets/js/lib/data-table/vfs_fonts.js') }}"></script>
    <script src="{{ asset('layout/assets/js/lib/data-table/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('layout/assets/js/lib/data-table/buttons.print.min.js') }}"></script>
    <script src="{{ asset('layout/assets/js/lib/data-table/buttons.colVis.min.js') }}"></script>
    <script src="{{ asset('layout/assets/js/init/datatables-init.js') }}"></script>


    <script type="text/javascript">
        $(document).ready(function() {
        $('#bootstrap-data-table-export').DataTable();
    } );
    </script>
@endpush