routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MahasiswaController;
use App\Http\Controllers\MatkulController;
use App\Http\Controllers\NilaiController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', [App\Http\Controllers\mhscekController::class, 'index'])->name('mhscek');

// Auth::routes();
Route::prefix('wp-admin')->group(function () {
    Auth::routes();
});
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('mahasiswa', MahasiswaController::class);
Route::resource('matkul', MatkulController::class);
Route::resource('nilai', NilaiController::class);
Route::get('/profile/index', [App\Http\Controllers\ProfileController::class, 'index'])->name('profile.index');
Route::get('/cek', [App\Http\Controllers\mhscekController::class, 'show'])->name('mhscek.show');
Route::get('/analisis', [App\Http\Controllers\analisisController::class, 'index'])->name('analisis.index');

app/Models/mahasiswa.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class mahasiswa extends Model
{
    protected $table = 'mahasiswa';
    protected $guarded = ['id'];
}

app/Http/Controllers/MahasiswaController.php
<?php

namespace App\Http\Controllers;

use App\Models\mahasiswa;
use App\Models\nilai;
use Illuminate\Http\Request;

class MahasiswaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index()
    {
        $mahasiswa = mahasiswa::all();
        return view('mahasiswa.index', compact(
            'mahasiswa'
        ));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $model = new mahasiswa;
        return view('mahasiswa.create', compact(
            'model'
        ));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nim' => 'required|unique:mahasiswa',
            'nama' => 'required',
            'angkatan' => 'required|min:2|max:4',
            'alamat' => 'required',
            'nohp' => 'required|min:11|max:13',
        ],
        [
            'nim.required' => 'NIM tidak boleh kosong',
            'nim.unique' => 'NIM sudah digunakan',
            'nama.required' => 'Nama tidak boleh kosong',
            'angkatan.required' => 'Angkatan tidak boleh kosong',
            'angkatan.min' => 'Minimal 2 karakter',
            'angkatan.max' => 'Maximal 4 karakter',
            'alamat.required' => 'Alamat tidak boleh kosong',
            'nohp.required' => 'No HP tidak boleh kosong',
            'nohp.min' => 'Minimal 11 karakter',
            'nohp.max' => 'Maximal 13 karakter',
        ]);

        mahasiswa::create([
            "nim" => $request['nim'],
            "nama" => $request['nama'],
            "angkatan" => $request['angkatan'],
            "alamat" => $request['alamat'],
            "nohp" => $request['nohp']
        ]);

        return redirect('mahasiswa');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\mahasiswa  $mahasiswa
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $mahasiswa = mahasiswa::where('id', $id)->first();
        return view('mahasiswa.show', compact('mahasiswa'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\mahasiswa  $mahasiswa
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $mahasiswa = mahasiswa::where('id', $id)->first();
        return view('mahasiswa.edit', compact('mahasiswa'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\mahasiswa  $mahasiswa
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            
            'nama' => 'required',
            'angkatan' => 'required|min:2|max:4',
            'alamat' => 'required',
            'nohp' => 'required|min:11|max:13',
        ],
        [
            
            'nama.required' => 'Nama tidak boleh kosong',
            'angkatan.required' => 'Angkatan tidak boleh kosong',
            'angkatan.min' => 'Minimal 2 karakter',
            'angkatan.max' => 'Maximal 4 karakter',
            'alamat.required' => 'Alamat tidak boleh kosong',
            'nohp.required' => 'No HP tidak boleh kosong',
            'nohp.min' => 'Minimal 11 karakter',
            'nohp.max' => 'Maximal 13 karakter',
        ]);

        $mahasiswa = mahasiswa::where('id', $id)->update([
            
            "nama" => $request['nama'],
            "angkatan" => $request['angkatan'],
            "alamat" => $request['alamat'],
            "nohp" => $request['nohp']
        ]);

        return redirect('mahasiswa');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\mahasiswa  $mahasiswa
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $query = mahasiswa::where('id', $id)->delete();
        return redirect('mahasiswa');
    }
}

resources/views/mahasiswa/create.blade.php
@extends('partial.master')

@section('content')
<div class="content">
    <div class="page-inner">
        <div class="page-header">
            <h4 class="page-title">Tambah Data Mahasiswa</h4>   
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">Form Tambah Data</div>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('mahasiswa.store') }}" method="POST">
                            @csrf
                                <div class="form-group">
                                    <label>NIM</label>
                                    <input type="text" name="nim" class="form-control @error('nim') is-invalid @enderror" placeholder="NIM" value="{{old('nim')}}">
                                    @error('nim')
                                        <div class="invalid-feedback">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label>Nama</label>
                                    <input type="text" name="nama" class="form-control @error('nama') is-invalid @enderror"  placeholder="Nama" value="{{old('nama')}}">
                                    @error('nama')
                                        <div class="invalid-feedback">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label>Angkatan</label>
                                    <input type="text" name="angkatan" class="form-control @error('angkatan') is-invalid @enderror" placeholder="Angkatan" value="{{old('angkatan')}}">
                                    @error('angkatan')
                                        <div class="invalid-feedback">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label>Alamat</label>
                                    <input type="text" name="alamat" class="form-control  @error('alamat') is-invalid @enderror" placeholder="Alamat" value="{{old('alamat')}}">
                                    @error('alamat')
                                        <div class="invalid-feedback">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label>Nomor Handphone</label>
                                    <input type="text" name="nohp" class="form-control @error('nohp') is-invalid @enderror"  placeholder="No HP" value="{{old('nohp')}}">
                                    @error('nohp')
                                        <div class="invalid-feedback">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="card-action">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                    <a href="{{route('mahasiswa.index')}}"><button type="button" class="btn btn-danger">Cancel</button></a>
                                </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
    
@endsection
			
		
	

resources/views/mahasiswa/edit.blade.php
@extends('partial.master')

@section('content')
<div class="content">
    <div class="page-inner">
        <div class="page-header">
            <h4 class="page-title">Edit Data Mahasiswa</h4>
            
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">Form Edit Data</div>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('mahasiswa.update', $mahasiswa->id) }}" method="post">
                            @csrf
                            @method('PUT')
                                <div class="form-group">
                                    <label>NIM</label>
                                    <input type="text" name="nim" class="form-control @error('nim') is-invalid @enderror" placeholder="NIM" value="{{old('nim', $mahasiswa->nim) }}" disabled>
                                    @error('nim')
                                        <div class="invalid-feedback">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label>Nama</label>
                                    <input type="text" name="nama" class="form-control @error('nama') is-invalid @enderror"  placeholder="Nama" value="{{old('nama', $mahasiswa->nama)}}">
                                    @error('nama')
                                        <div class="invalid-feedback">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label>Angkatan</label>
                                    <input type="text" name="angkatan" class="form-control @error('angkatan') is-invalid @enderror" placeholder="Angkatan" value="{{old('angkatan', $mahasiswa->angkatan)}}">
                                    @error('angkatan')
                                        <div class="invalid-feedback">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label>Alamat</label>
                                    <input type="text" name="alamat" class="form-control  @error('alamat') is-invalid @enderror" placeholder="Alamat" value="{{old('alamat', $mahasiswa->alamat)}}">
                                    @error('alamat')
                                        <div class="invalid-feedback">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label>Nomor Handphone</label>
                                    <input type="text" name="nohp" class="form-control @error('nohp') is-invalid @enderror"  placeholder="No HP" value="{{old('nohp', $mahasiswa->nohp)}}">
                                    @error('nohp')
                                        <div class="invalid-feedback">{{ $message }}</div>
                                    @enderror
                                </div>
                                <div class="card-action">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                    <a href="{{route('mahasiswa.index')}}"><button type="button" class="btn btn-danger">Cancel</button></a>
                                </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
    
@endsection

resources/views/mahasiswa/index.blade.php
@extends('partial.master')
@push('style')
    <link rel="stylesheet" href="{{ asset('layout/assets/css/lib/datatable/dataTables.bootstrap.min.css') }}">
@endpush
@section('content')
    <div class="content">
        <div class="animated fadeIn">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="d-flex align-items-center">
                                <h4 class="card-title">Data Mahasiswa</h4>
                                
                                <a href="{{ route('mahasiswa.create') }}" class="btn btn-primary btn-round ml-auto">
                                    Tambah Data
                                </a>
                                
                            </div>
                        </div>
                        <div class="card-body">
                            <table id="bootstrap-data-table" class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th width=25%>NIM</th>
                                        <th width=35%>Nama</th>
                                        <th width=20%>Angkatan</th>
                                        <th width=20%>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($mahasiswa as $key=>$data)
                                    <tr>
                                        <td>{{ $data->nim }}</td>
                                        <td>{{ $data->nama }}</td>
                                        <td>{{ $data->angkatan }}</td>
                                        <td>
                                            <form action="{{route('mahasiswa.destroy', $data->id)}}" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <a href="{{ route('mahasiswa.show', $data->id)}}" class="btn btn-info btn-sm"><i class="fa fa-info" aria-hidden="true"></i></a>
                                            <a href="{{ route('mahasiswa.edit', $data->id)}}" class="btn btn-primary btn-sm"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                                            <button type="submit" class="btn btn-danger my-1 btn-sm fa fa-trash"></button>
                                            </form>
                                        </td>
                                    </tr>
                                    @endforeach             
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>


            </div>
        </div><!-- .animated -->
    </div>
@endsection

@push('scripts')
    <script src="{{ asset('layout/assets/js/lib/data-table/dataTables.bootstrap.min.js') }}"></script>
    <script src="{{ asset('layout/assets/js/lib/data-table/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('layout/assets/js/lib/data-table/buttons.bootstrap.min.js') }}"></script>
    <script src="{{ asset('layout/assets/js/lib/data-table/jszip.min.js') }}"></script>
    <script src="{{ asset('layout/assets/js/lib/data-table/vfs_fonts.js') }}"></script>
    <script src="{{ asset('layout/assets/js/lib/data-table/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('layout/assets/js/lib/data-table/buttons.print.min.js') }}"></script>
    <script src="{{ asset('layout/assets/js/lib/data-table/buttons.colVis.min.js') }}"></script>
    <script src="{{ asset('layout/assets/js/init/datatables-init.js') }}"></script>


    <script type="text/javascript">
        $(document).ready(function() {
        $('#bootstrap-data-table-export').DataTable();
    } );
    </script>
@endpush

resources/views/mahasiswa/show.blade.php
@extends('partial.master')

@section('content')
<div class="content">
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="d-flex align-items-center"></div>
                            <h1 class="h3 mb-2 text-gray-800">Detail Mahasiswa</h1>
                        </div>
                        <div class="card-body">
                            <p>NIP : {{ $mahasiswa->nim }}</p>
                            <p>Nama : {{ $mahasiswa->nama }}</p>
                            <p>Angkatan : {{ $mahasiswa->angkatan }}</p>
                            <p>Alamat : {{ $mahasiswa->alamat }}</p>
                            <p>Nomor HP : {{ $mahasiswa->nohp }}</p>

                            <a class="btn btn-primary" href="{{ route('mahasiswa.index') }}">Kembali</a>
                        </div>
                    </div>            
                </div>
            </div>
        </div>
    </div>
</div>   
@endsection