routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MahasiswaController;
use App\Http\Controllers\MatkulController;
use App\Http\Controllers\NilaiController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', [App\Http\Controllers\mhscekController::class, 'index'])->name('mhscek');

// Auth::routes();
Route::prefix('wp-admin')->group(function () {
    Auth::routes();
});
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('mahasiswa', MahasiswaController::class);
Route::resource('matkul', MatkulController::class);
Route::resource('nilai', NilaiController::class);
Route::get('/profile/index', [App\Http\Controllers\ProfileController::class, 'index'])->name('profile.index');
Route::get('/cek', [App\Http\Controllers\mhscekController::class, 'show'])->name('mhscek.show');
Route::get('/analisis', [App\Http\Controllers\analisisController::class, 'index'])->name('analisis.index');

app/Models/nilai.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class nilai extends Model
{
    protected $table = 'nilai';
    protected $guarded = ['id'];
    
    public function mahasiswa()
    {
        return $this->belongsTo(Mahasiswa::class);
    }
    
    public function matkul()
    {
        return $this->belongsTo(Matkul::class);
    }
}

app/Http/Controllers/NilaiController.php
<?php

namespace App\Http\Controllers;

use App\Models\nilai;
use App\Models\mahasiswa;
use App\Models\matkul;
use Illuminate\Http\Request;

class NilaiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $matkul = matkul::all()->first();
        $nilai = nilai::all();
        return view('nilai.index', compact(
            'matkul','nilai'
        ));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $mahasiswa = mahasiswa::all();
        $matkul = matkul::all();
        return view('nilai.create', compact(
            'mahasiswa','matkul'
        ));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            
            'mahasiswa_id' => 'required',
            'na_matkul1' => 'required',
            'na_matkul2' => 'required',
            'na_matkul3' => 'required',
            'na_matkul4' => 'required',
            'na_matkul5' => 'required',
            'na_matkul6' => 'required',
            'na_matkul7' => 'required',
            'na_matkul8' => 'required',
            'na_matkul9' => 'required',
            'na_matkul10' => 'required',
            'na_matkul11' => 'required',
            'na_matkul12' => 'required',
            'na_matkul13' => 'required',
            'na_matkul14' => 'required',
            'na_matkul15' => 'required',
            'na_matkul16' => 'required',
            'na_matkul17' => 'required',
            'na_matkul18' => 'required',
            'na_matkul19' => 'required',
            'na_matkul20' => 'required',
            'na_matkul21' => 'required',
            'na_matkul22' => 'required',
            'na_matkul23' => 'required',
            'na_matkul24' => 'required'
        ],
        [
            'mahasiswa_id.required' => 'Mahasiswa tidak boleh kosong',
            'na_matkul1.required' => 'Nilai tidak boleh kosong',
            'na_matkul2.required' => 'Nilai tidak boleh kosong',
            'na_matkul3.required' => 'Nilai tidak boleh kosong',
            'na_matkul4.required' => 'Nilai tidak boleh kosong',
            'na_matkul5.required' => 'Nilai tidak boleh kosong',
            'na_matkul6.required' => 'Nilai tidak boleh kosong',
            'na_matkul7.required' => 'Nilai tidak boleh kosong',
            'na_matkul8.required' => 'Nilai tidak boleh kosong',
            'na_matkul9.required' => 'Nilai tidak boleh kosong',
            'na_matkul10.required' => 'Nilai tidak boleh kosong',
            'na_matkul11.required' => 'Nilai tidak boleh kosong',
            'na_matkul12.required' => 'Nilai tidak boleh kosong',
            'na_matkul13.required' => 'Nilai tidak boleh kosong',
            'na_matkul14.required' => 'Nilai tidak boleh kosong',
            'na_matkul15.required' => 'Nilai tidak boleh kosong',
            'na_matkul16.required' => 'Nilai tidak boleh kosong',
            'na_matkul17.required' => 'Nilai tidak boleh kosong',
            'na_matkul18.required' => 'Nilai tidak boleh kosong',
            'na_matkul19.required' => 'Nilai tidak boleh kosong',
            'na_matkul20.required' => 'Nilai tidak boleh kosong',
            'na_matkul21.required' => 'Nilai tidak boleh kosong',
            'na_matkul22.required' => 'Nilai tidak boleh kosong',
            'na_matkul23.required' => 'Nilai tidak boleh kosong',
            'na_matkul24.required' => 'Nilai tidak boleh kosong'
        ]);

        // $matkul = matkul::where('id', $request['matkul_id'])->first();
        
        nilai::create([
            "mahasiswa_id" => $request['mahasiswa_id'],
            "na_matkul1" => $request['na_matkul1'],
            "na_matkul2" => $request['na_matkul2'],
            "na_matkul3" => $request['na_matkul3'],
            "na_matkul4" => $request['na_matkul4'],
            "na_matkul5" => $request['na_matkul5'],
            "na_matkul6" => $request['na_matkul6'],
            "na_matkul7" => $request['na_matkul7'],
            "na_matkul8" => $request['na_matkul8'],
            "na_matkul9" => $request['na_matkul9'],
            "na_matkul10" => $request['na_matkul10'],
            "na_matkul11" => $request['na_matkul11'],
            "na_matkul12" => $request['na_matkul12'],
            "na_matkul13" => $request['na_matkul13'],
            "na_matkul14" => $request['na_matkul14'],
            "na_matkul15" => $request['na_matkul15'],
            "na_matkul16" => $request['na_matkul16'],
            "na_matkul17" => $request['na_matkul17'],
            "na_matkul18" => $request['na_matkul18'],
            "na_matkul19" => $request['na_matkul19'],
            "na_matkul20" => $request['na_matkul20'],
            "na_matkul21" => $request['na_matkul21'],
            "na_matkul22" => $request['na_matkul22'],
            "na_matkul23" => $request['na_matkul23'],
            "na_matkul24" => $request['na_matkul24'],
        ]);
        return redirect('nilai');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\nilai  $nilai
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $matkul = matkul::all();
        $d_nilai = nilai::all();
        $nilai = nilai::where('id', $id)->first();
        return view('nilai.show', compact('nilai','matkul','d_nilai'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\nilai  $nilai
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $mahasiswa = mahasiswa::all();
        $matkul = matkul::all();
        $nilai = nilai::where('id', $id)->first();
        return view('nilai.edit', compact('matkul','mahasiswa','nilai'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\nilai  $nilai
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            
            'mahasiswa_id' => 'required',
            'matkul_id' => 'required',
            'nilai' => 'required',
        ],
        [
            
            'mahasiswa_id.required' => 'Mahasiswa tidak boleh kosong',
            'matkul_id.required' => 'Mata Kuliah tidak boleh kosong',
            'nilai.required' => 'Nilai tidak boleh kosong',
        ]);

        

        $tanya = nilai::where('id', $id)->update([
            "mahasiswa_id" => $request['mahasiswa_id'],
            "matkul_id" => $request['matkul_id'],
            "nilai" => $request['nilai'],
            "nilaiakhir" => $request['nilai'] * $matkul->sks
        ]);
        return redirect('nilai');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\nilai  $nilai
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $query = nilai::where('id', $id)->delete();
        return redirect('nilai');
    }
}

resources/views/nilai/create.blade.php
@extends('partial.master')

@section('content')
<div class="content">
    <div class="page-inner">
        <div class="page-header">
            <h4 class="page-title">Tambah Data Nilai</h4>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">Form Tambah Data</div>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('nilai.store') }}" method="POST">
                        @csrf
                            
                                <div class="form-group">
                                        <label>Mahasiswa</label>
                                        <select class="form-control @error('mahasiswa_id') is-invalid @enderror" name="mahasiswa_id">
                                            <option value="0" selected disabled>-- Pilih Mahasiswa --</option>
                                            @foreach ($mahasiswa as $data)
                                                @if (old('mahasiswa_id') == $data->id)
                                                    <option value="{{ $data->id }}"> {{ $data->nim }} - {{$data->nama}} </option>
                                                @else 
                                                    <option value="{{ $data->id }}"> {{ $data->nim }} - {{$data->nama}} </option>
                                                @endif
                                            @endforeach
                                        </select>
                                        @error('mahasiswa_id')
                                            <div class="invalid-feedback">{{ $message }}</div>
                                        @enderror
                                        </select>
                                </div>
                                <br>
                                <h3><b>DATA NILAI MAHASISWA</b> </h3>
                                        @foreach ($matkul as $key=>$data)
                                            <div class="form-group">
                                                <label>{{$data->nama}}</label>
                                                <input type="text" name="na_matkul{{$data->id}}" class="form-control @error('na_matkul{{$data->id}}') is-invalid @enderror" placeholder="Masukan Nilai">
                                                @error('na_matkul{{$data->id}}')
                                                    <div class="invalid-feedback">{{ $message }}</div>
                                                @enderror
                                            </div>
                                        @endforeach
                                <div class="card-action">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                    <a href="{{route('nilai.index')}}"><button type="button" class="btn btn-danger">Cancel</button></a>
                                </div>
                            
                        </form>     
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
    
@endsection
			
		
	

resources/views/nilai/edit.blade.php
@extends('partial.master')

@section('content')
<div class="content">
    <div class="page-inner">
        <div class="page-header">
            <h4 class="page-title">Tambah Data Nilai</h4>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">Form Tambah Data</div>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('nilai.store', $nilai->id) }}" method="POST">
                        @csrf
                                <div class="form-group">
                                        <label>Mahasiswa</label>
                                        <select class="form-control @error('mahasiswa_id') is-invalid @enderror" name="mahasiswa_id">
                                            <option value="0" selected disabled>-- Pilih Mahasiswa --</option>
                                            @foreach ($mahasiswa as $data)
                                                @if (old('mahasiswa_id', $nilai->mahasiswa_id) == $data->id)
                                                    <option value="{{ $data->id }}" selected> {{ $data->nim }} - {{$data->nama}} </option>
                                                @else 
                                                    <option value="{{ $data->id }}"> {{ $data->nim }} - {{$data->nama}} </option>
                                                @endif
                                            @endforeach
                                        </select>
                                        @error('mahasiswa_id')
                                            <div class="invalid-feedback">{{ $message }}</div>
                                        @enderror
                                        </select>
                                </div>
                                <br>
                                <h3> <b>DATA NILAI MAHASISWA</b> </h3>
                                
                                        @foreach ($matkul as $key=>$data)
                                            <div class="form-group">
                                                <label>{{$data->nama}}</label>
                                                <input type="text" name="na_matkul{{$data->id}}" class="form-control @error('na_matkul{{$data->id}}') is-invalid @enderror" placeholder="Masukan Nilai" value="{{ old('na_matkul<?= {{$data->id}};?>', $nilai->na_matkul<?= {{$data->id}}; ?>) }}">
                                                @error('na_matkul{{$data->id}}')
                                                    <div class="invalid-feedback">{{ $message }}</div>
                                                @enderror
                                            </div>
                                        @endforeach
                                        
                                <div class="card-action">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                    <a href="{{route('nilai.index')}}"><button type="button" class="btn btn-danger">Cancel</button></a>
                                </div>
                            
                        </form>     
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
    
@endsection
			
		
	

resources/views/nilai/index.blade.php
@extends('partial.master')
@push('style')
    <link rel="stylesheet" href="{{ asset('layout/assets/css/lib/datatable/dataTables.bootstrap.min.css') }}">
@endpush
@section('content')
    <div class="content">
        <div class="animated fadeIn">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="d-flex align-items-center">
                                <h4 class="card-title">Data Nilai Mata Kuliah</h4>
                                
                                <a href="{{ route('nilai.create') }}" class="btn btn-primary btn-round ml-auto">
                                    Tambah Data  
                                </a>
                                
                            </div>
                        </div>
                        <div class="card-body">
                            <table id="bootstrap-data-table" class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th width=20%>NIM</th>
                                        <th width=40%>Nama Mahasiswa</th>
                                        <th width=20%>Nilai</th>
                                        <th width=20%>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    
                                    @foreach ($nilai as $key=>$data)
                                        <tr>
                                            <td>{{ $data->mahasiswa->nim }}</td>
                                            <td>{{ $data->mahasiswa->nama }}</td>
                                            <td>Tersimpan</td>
                                            <td>
                                            <form action="{{route('nilai.destroy', $data->id)}}" method="POST">
                                                @csrf
                                                @method('DELETE')
                                                {{-- <a href="{{route('nilai.show', $data->id)}}" class="btn btn-primary btn-sm"><i class="fa fa-info" aria-hidden="true"></i></a> --}}
                                                <a href="{{route('nilai.edit', $data->id)}}" class="btn btn-primary btn-sm"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                                                <button type="submit" class="btn btn-danger my-1 btn-sm fa fa-trash">
                                            </form>
                                            </td>
                                        </tr>
                                    @endforeach              
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>


            </div>
        </div><!-- .animated -->
    </div>
@endsection

@push('scripts')
    <script src="{{ asset('layout/assets/js/lib/data-table/dataTables.bootstrap.min.js') }}"></script>
    <script src="{{ asset('layout/assets/js/lib/data-table/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('layout/assets/js/lib/data-table/buttons.bootstrap.min.js') }}"></script>
    <script src="{{ asset('layout/assets/js/lib/data-table/jszip.min.js') }}"></script>
    <script src="{{ asset('layout/assets/js/lib/data-table/vfs_fonts.js') }}"></script>
    <script src="{{ asset('layout/assets/js/lib/data-table/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('layout/assets/js/lib/data-table/buttons.print.min.js') }}"></script>
    <script src="{{ asset('layout/assets/js/lib/data-table/buttons.colVis.min.js') }}"></script>
    <script src="{{ asset('layout/assets/js/init/datatables-init.js') }}"></script>


    <script type="text/javascript">
        $(document).ready(function() {
        $('#bootstrap-data-table-export').DataTable();
    } );
    </script>
@endpush